movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list_movies, name='index'),
    path('search/', views.search_movies, name='search'), 
    path('create/', views.create_movie, name='create'),
    path('<int:movie_id>/', views.detail_movie, name='detail'),
]

moviesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

movies/models.py
from django.db import models

# Create your models here.

staticpages/models.py
from django.db import models

# Create your models here.

movies/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from .temp_data import movie_data

def detail_movie(request, movie_id):
    context = {'movie': movie_data[movie_id - 1]}
    return render(request, 'movies/detail.html', context)
    
def list_movies(request):
    context = {"movie_list": movie_data}
    return render(request, 'movies/index.html', context)

def search_movies(request):
    context = {}
    if request.GET.get('query', False):
        context = {
            "movie_list": [
                m for m in movie_data
                if request.GET['query'].lower() in m['name'].lower()
            ]
        }
    return render(request, 'movies/search.html', context)

def create_movie(request):
    if request.method == 'POST':
        movie_data.append({
            'name': request.POST['name'],
            'release_year': request.POST['release_year'],
            'poster_url': request.POST['poster_url']
        })
        return HttpResponseRedirect(
            reverse('movies:detail', args=(len(movie_data), )))
    else:
        return render(request, 'movies/create.html', {})

staticpages/views.py
from django.shortcuts import render

def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)

def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Filme</h2>
<form method="POST" action="{% url 'movies:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" />
    </p>
    <p>
        <label for="id_release_year">Ano de Lançamento:</label>
        <input type="number" name="release_year" id="id_release_year" />
    </p>
    <p>
        <label for="id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" />
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block title %}
{{ movie.name }} ({{ movie.release_year }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Filme {{ movie.name }} ({{ movie.release_year }})</h2>

<section class="dados-de-filme">
    <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
    <ul>
        <li>Nome: {{ movie.name }}</li>
        <li>Ano de Lançamento: {{ movie.release_year }} </li>
    </ul>
</section>

{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Filmes</h2>
<section>
    <p>Muitos resultados? <a href="{% url 'movies:search' %}">Buscar Filmes</a></p>
    <p>Não encontrou o filme? <a href="{% url 'movies:create' %}">Adicionar Novo Filme</a></p>
</section>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <a href="{% url 'movies:detail' forloop.counter %}"><img src="{{ movie.poster_url }}"
                alt="Poster do filme {{ movie.name}}"></a>
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %}

{% endblock content %}

movies/templates/movies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}

staticpages/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'movies:index' %}">Filmes</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Watch that film!</i></h1>
<p>A Página para Comunidade Resenhadora de Filmes</p>
{% endblock content %}